// <auto-generated />
namespace CompanyDemo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class project_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(project_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201709141107063_project_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
